springcloud:
  collaborators: user1, user2

issuebot:
  github:
    repositories:
      - organization: spencergibb
        name: issuebot-test1
        collaborators: ${springcloud.collaborators}
      - organization: spencergibb
        name: issuebot-test2
        collaborators: ${springcloud.collaborators}
  triage:
    label:
      spencergibb: "inbox"
  feedback:
    spencergibb:
      required_label: "waiting-for-feedback"
      provided_label: "feedback-provided"
      reminder_label: "feedback-reminder"
      reminder_comment: >
        If you would like us to look at this issue, please provide the requested
        information. If the information is not provided within the next 7 days this issue
        will be closed.
      close_comment: >
        Closing due to lack of requested feedback. If you would like us to look at this
        issue, please provide the requested information and we will re-open the issue.